export const BIBLE_VERSES = [
    { text: "No princípio criou Deus o céu e a terra.", ref: "Gênesis 1:1" },
    { text: "E disse Deus: Haja luz; e houve luz.", ref: "Gênesis 1:3" },
    { text: "E criou Deus o homem à sua imagem.", ref: "Gênesis 1:27" },
    { text: "Viu Deus tudo quanto tinha feito, e eis que era muito bom.", ref: "Gênesis 1:31" },
    { text: "Não é bom que o homem esteja só.", ref: "Gênesis 2:18" },
    { text: "Comerás o pão com o suor do teu rosto.", ref: "Gênesis 3:19" },
    { text: "O Senhor é o meu pastor, nada me faltará.", ref: "Salmos 23:1" },
    { text: "Em verdes pastagens me faz repousar.", ref: "Salmos 23:2" },
    { text: "Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum.", ref: "Salmos 23:4" },
    { text: "Certamente que a bondade e a misericórdia me seguirão todos os dias da minha vida.", ref: "Salmos 23:6" },
    { text: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.", ref: "Salmos 46:1" },
    { text: "Aquietai-vos, e sabei que eu sou Deus.", ref: "Salmos 46:10" },
    { text: "Cria em mim, ó Deus, um coração puro.", ref: "Salmos 51:10" },
    { text: "Lâmpada para os meus pés é tua palavra, e luz para o meu caminho.", ref: "Salmos 119:105" },
    { text: "Os que confiam no Senhor serão como o monte de Sião, que não se abala, mas permanece para sempre.", ref: "Salmos 125:1" },
    { text: "Se o Senhor não edificar a casa, em vão trabalham os que a edificam.", ref: "Salmos 127:1" },
    { text: "Eis que os filhos são herança do Senhor.", ref: "Salmos 127:3" },
    { text: "Louvai ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre.", ref: "Salmos 136:1" },
    { text: "Sonda-me, ó Deus, e conhece o meu coração.", ref: "Salmos 139:23" },
    { text: "Todo o que respira louve ao Senhor.", ref: "Salmos 150:6" },
    { text: "O temor do Senhor é o princípio da sabedoria.", ref: "Provérbios 1:7" },
    { text: "Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento.", ref: "Provérbios 3:5" },
    { text: "Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.", ref: "Provérbios 3:6" },
    { text: "Guarda o teu coração, porque dele procedem as fontes da vida.", ref: "Provérbios 4:23" },
    { text: "O ódio excita contendas, mas o amor cobre todas as transgressões.", ref: "Provérbios 10:12" },
    { text: "A resposta branda desvia o furor, mas a palavra dura suscita a ira.", ref: "Provérbios 15:1" },
    { text: "O coração alegre aformoseia o rosto.", ref: "Provérbios 15:13" },
    { text: "Antes da ruína vai a soberba, e diante da queda a altivez de espírito.", ref: "Provérbios 16:18" },
    { text: "O amigo ama em todo o tempo; e para a angústia nasce o irmão.", ref: "Provérbios 17:17" },
    { text: "O coração alegre serve de bom remédio.", ref: "Provérbios 17:22" },
    { text: "Como o ferro com o ferro se aguça, assim o homem afia o rosto do seu amigo.", ref: "Provérbios 27:17" },
    { text: "Tudo tem o seu tempo determinado.", ref: "Eclesiastes 3:1" },
    { text: "Melhor é serem dois do que um.", ref: "Eclesiastes 4:9" },
    { text: "Lembra-te do teu Criador nos dias da tua mocidade.", ref: "Eclesiastes 12:1" },
    { text: "Não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus.", ref: "Isaías 41:10" },
    { text: "Mas os que esperam no Senhor renovarão as forças.", ref: "Isaías 40:31" },
    { text: "Eis que a virgem conceberá, e dará à luz um filho, e chamará o seu nome Emanuel.", ref: "Isaías 7:14" },
    { text: "Porque um menino nos nasceu, um filho se nos deu.", ref: "Isaías 9:6" },
    { text: "Busca ao Senhor enquanto se pode achar, invocai-o enquanto está perto.", ref: "Isaías 55:6" },
    { text: "As misericórdias do Senhor são a causa de não sermos consumidos.", ref: "Lamentações 3:22" },
    { text: "Novas são cada manhã; grande é a tua fidelidade.", ref: "Lamentações 3:23" },
    { text: "Buscar-me-eis, e me achareis, quando me buscardes de todo o vosso coração.", ref: "Jeremias 29:13" },
    { text: "Clama a mim, e responder-te-ei.", ref: "Jeremias 33:3" },
    { text: "O meu povo foi destruído, porque lhe faltou o conhecimento.", ref: "Oséias 4:6" },
    { text: "E será que todo aquele que invocar o nome do Senhor será salvo.", ref: "Joel 2:32" },
    { text: "Buscai o bem, e não o mal, para que vivais.", ref: "Amós 5:14" },
    { text: "O Senhor é bom, uma fortaleza no dia da angústia.", ref: "Naum 1:7" },
    { text: "Alegra-te muito, ó filha de Sião.", ref: "Zacarias 9:9" },
    { text: "Bem-aventurados os pobres de espírito, porque deles é o reino dos céus.", ref: "Mateus 5:3" },
    { text: "Bem-aventurados os que choram, porque eles serão consolados.", ref: "Mateus 5:4" },
    { text: "Bem-aventurados os mansos, porque eles herdarão a terra.", ref: "Mateus 5:5" },
    { text: "Bem-aventurados os que têm fome e sede de justiça, porque eles serão fartos.", ref: "Mateus 5:6" },
    { text: "Bem-aventurados os misericordiosos, porque eles alcançarão misericórdia.", ref: "Mateus 5:7" },
    { text: "Bem-aventurados os limpos de coração, porque eles verão a Deus.", ref: "Mateus 5:8" },
    { text: "Bem-aventurados os pacificadores, porque eles serão chamados filhos de Deus.", ref: "Mateus 5:9" },
    { text: "Vós sois o sal da terra.", ref: "Mateus 5:13" },
    { text: "Vós sois a luz do mundo.", ref: "Mateus 5:14" },
    { text: "Assim resplandeça a vossa luz diante dos homens.", ref: "Mateus 5:16" },
    { text: "Amai a vossos inimigos, bendizei os que vos maldizem.", ref: "Mateus 5:44" },
    { text: "Portanto, sede vós perfeitos.", ref: "Mateus 5:48" },
    { text: "Mas, quando tu orares, entra no teu aposento.", ref: "Mateus 6:6" },
    { text: "Pai nosso, que estás nos céus, santificado seja o teu nome.", ref: "Mateus 6:9" },
    { text: "Venha o teu reino, seja feita a tua vontade.", ref: "Mateus 6:10" },
    { text: "O pão nosso de cada dia nos dá hoje.", ref: "Mateus 6:11" },
    { text: "Não ajunteis tesouros na terra.", ref: "Mateus 6:19" },
    { text: "Ninguém pode servir a dois senhores.", ref: "Mateus 6:24" },
    { text: "Buscaí primeiro o reino de Deus, e a sua justiça.", ref: "Mateus 6:33" },
    { text: "Não vos inquieteis pelo dia de amanhã.", ref: "Mateus 6:34" },
    { text: "Não julgueis, para que não sejais julgados.", ref: "Mateus 7:1" },
    { text: "Pedi, e dar-se-vos-á; buscai, e encontrareis.", ref: "Mateus 7:7" },
    { text: "Entrai pela porta estreita.", ref: "Mateus 7:13" },
    { text: "Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.", ref: "Mateus 11:28" },
    { text: "Tomai sobre vós o meu jugo, e aprendei de mim, que sou manso e humilde de coração.", ref: "Mateus 11:29" },
    { text: "Porque o meu jugo é suave e o meu fardo é leve.", ref: "Mateus 11:30" },
    { text: "Pois onde estiverem dois ou três reunidos em meu nome, aí estou eu no meio deles.", ref: "Mateus 18:20" },
    { text: "Amarás o Senhor teu Deus de todo o teu coração.", ref: "Mateus 22:37" },
    { text: "Amarás o teu próximo como a ti mesmo.", ref: "Mateus 22:39" },
    { text: "Ide, portanto, fazei discípulos de todas as nações.", ref: "Mateus 28:19" },
    { text: "E eis que estou convosco todos os dias, até a consumação dos séculos.", ref: "Mateus 28:20" },
    { text: "Porque para Deus nada é impossível.", ref: "Lucas 1:37" },
    { text: "Glória a Deus nas alturas, Paz na terra, boa vontade para com os homens.", ref: "Lucas 2:14" },
    { text: "Amai, pois, a vossos inimigos.", ref: "Lucas 6:35" },
    { text: "Dai, e ser-vos-á dado.", ref: "Lucas 6:38" },
    { text: "Aquele que é fiel no pouco, também é fiel no muito.", ref: "Lucas 16:10" },
    { text: "No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.", ref: "João 1:1" },
    { text: "E o Verbo se fez carne, e habitou entre nós.", ref: "João 1:14" },
    { text: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito.", ref: "João 3:16" },
    { text: "O vento assopra onde quer.", ref: "João 3:8" },
    { text: "Aquele que crê no Filho tem a vida eterna.", ref: "João 3:36" },
    { text: "Mas aquele que beber da água que eu lhe der nunca terá sede.", ref: "João 4:14" },
    { text: "Deus é Espírito, e importa que os que o adoram o adorem em espírito e em verdade.", ref: "João 4:24" },
    { text: "Examinai as Escrituras.", ref: "João 5:39" },
    { text: "Eu sou o pão da vida.", ref: "João 6:35" },
    { text: "Conhecereis a verdade, e a verdade vos libertará.", ref: "João 8:32" },
    { text: "Se, pois, o Filho vos libertar, verdadeiramente sereis livres.", ref: "João 8:36" },
    { text: "Eu sou o bom pastor; o bom pastor dá a sua vida pelas ovelhas.", ref: "João 10:11" },
    { text: "As minhas ovelhas ouvem a minha voz.", ref: "João 10:27" },
    { text: "Eu sou a ressurreição e a vida.", ref: "João 11:25" },
    { text: "Jesus chorou.", ref: "João 11:35" },
    { text: "Um novo mandamento vos dou: Que vos ameis uns aos outros.", ref: "João 13:34" },
    { text: "Não se turbe o vosso coração.", ref: "João 14:1" },
    { text: "Na casa de meu Pai há muitas moradas.", ref: "João 14:2" },
    { text: "Eu sou o caminho, e a verdade e a vida.", ref: "João 14:6" },
    { text: "Se me amardes, guardareis os meus mandamentos.", ref: "João 14:15" },
    { text: "Deixo-vos a paz, a minha paz vos dou.", ref: "João 14:27" },
    { text: "Eu sou a videira verdadeira, e meu Pai é o lavrador.", ref: "João 15:1" },
    { text: "Vós sois meus amigos, se fizerdes o que eu vos mando.", ref: "João 15:14" },
    { text: "No mundo tereis aflições, mas tende bom ânimo, eu venci o mundo.", ref: "João 16:33" },
    { text: "E recebereis a virtude do Espírito Santo.", ref: "Atos 1:8" },
    { text: "Arrependei-vos, e cada um de vós seja batizado.", ref: "Atos 2:38" },
    { text: "Não tenho prata nem ouro; mas o que tenho isso te dou.", ref: "Atos 3:6" },
    { text: "Porque não podemos deixar de falar do que temos visto e ouvido.", ref: "Atos 4:20" },
    { text: "Mais importa obedecer a Deus do que aos homens.", ref: "Atos 5:29" },
    { text: "Crê no Senhor Jesus Cristo e serás salvo, tu e a tua casa.", ref: "Atos 16:31" },
    { text: "Mais bem-aventurada coisa é dar do que receber.", ref: "Atos 20:35" },
    { text: "Porque não me envergonho do evangelho de Cristo.", ref: "Romanos 1:16" },
    { text: "Porque todos pecaram e destituídos estão da glória de Deus.", ref: "Romanos 3:23" },
    { text: "Mas Deus prova o seu amor para conosco.", ref: "Romanos 5:8" },
    { text: "Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna.", ref: "Romanos 6:23" },
    { text: "Agora, pois, nenhuma condenação há para os que estão em Cristo Jesus.", ref: "Romanos 8:1" },
    { text: "O Espírito ajuda as nossas fraquezas.", ref: "Romanos 8:26" },
    { text: "Sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus.", ref: "Romanos 8:28" },
    { text: "Se Deus é por nós, quem será contra nós?", ref: "Romanos 8:31" },
    { text: "Quem nos separará do amor de Cristo?", ref: "Romanos 8:35" },
    { text: "Mas em todas estas coisas somos mais do que vencedores.", ref: "Romanos 8:37" },
    { text: "A fé é pelo ouvir, e o ouvir pela palavra de Deus.", ref: "Romanos 10:17" },
    { text: "Alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração.", ref: "Romanos 12:12" },
    { text: "Não te deixes vencer do mal, mas vence o mal com o bem.", ref: "Romanos 12:21" },
    { text: "A ninguém devais coisa alguma, a não ser o amor.", ref: "Romanos 13:8" },
    { text: "Porque nenhum de nós vive para si, e nenhum morre para si.", ref: "Romanos 14:7" },
    { text: "Certamente a palavra da cruz é loucura para os que perecem.", ref: "1 Coríntios 1:18" },
    { text: "Mas nós temos a mente de Cristo.", ref: "1 Coríntios 2:16" },
    { text: "Vós sois o templo de Deus.", ref: "1 Coríntios 3:16" },
    { text: "Tudo me é lícito, mas nem tudo me convém.", ref: "1 Coríntios 6:12" },
    { text: "Fugi da prostituição.", ref: "1 Coríntios 6:18" },
    { text: "A ciência incha, mas o amor edifica.", ref: "1 Coríntios 8:1" },
    { text: "Aquele, pois, que cuida estar em pé, olhe não caia.", ref: "1 Coríntios 10:12" },
    { text: "Sede meus imitadores, como também eu de Cristo.", ref: "1 Coríntios 11:1" },
    { text: "Ainda que eu falasse as línguas dos homens e dos anjos, e não tivesse amor, seria como o metal que soa.", ref: "1 Coríntios 13:1" },
    { text: "O amor é sofredor, é benigno; o amor não é invejoso.", ref: "1 Coríntios 13:4" },
    { text: "O amor nunca falha.", ref: "1 Coríntios 13:8" },
    { text: "Agora, pois, permanecem a fé, a esperança e o amor.", ref: "1 Coríntios 13:13" },
    { text: "Todas as vossas coisas sejam feitas com amor.", ref: "1 Coríntios 16:14" },
    { text: "Porque andamos por fé, e não por vista.", ref: "2 Coríntios 5:7" },
    { text: "Se alguém está em Cristo, nova criatura é.", ref: "2 Coríntios 5:17" },
    { text: "Deus ama ao que dá com alegria.", ref: "2 Coríntios 9:7" },
    { text: "A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza.", ref: "2 Coríntios 12:9" },
    { text: "Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim.", ref: "Gálatas 2:20" },
    { text: "Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança.", ref: "Gálatas 5:22" },
    { text: "Não erreis: Deus não se deixa escarnecer.", ref: "Gálatas 6:7" },
    { text: "E não nos cansemos de fazer bem.", ref: "Gálatas 6:9" },
    { text: "Pela graça sois salvos, por meio da fé.", ref: "Efésios 2:8" },
    { text: "Porque somos feitura sua, criados em Cristo Jesus.", ref: "Efésios 2:10" },
    { text: "Há um só Senhor, uma só fé, um só batismo.", ref: "Efésios 4:5" },
    { text: "Irai-vos, e não pequeis; não se ponha o sol sobre a vossa ira.", ref: "Efésios 4:26" },
    { text: "Vós, maridos, amai vossas mulheres, como também Cristo amou a igreja.", ref: "Efésios 5:25" },
    { text: "Vós, filhos, sede obedientes a vossos pais.", ref: "Efésios 6:1" },
    { text: "Revestí-vos de toda a armadura de Deus.", ref: "Efésios 6:11" },
    { text: "Porque para mim o viver é Cristo, e o morrer é ganho.", ref: "Filipenses 1:21" },
    { text: "Nada façais por contenda ou por vanglória.", ref: "Filipenses 2:3" },
    { text: "De sorte que haja em vós o mesmo sentimento que houve também em Cristo Jesus.", ref: "Filipenses 2:5" },
    { text: "Para que ao nome de Jesus se dobre todo o joelho.", ref: "Filipenses 2:10" },
    { text: "Fazei todas as coisas sem murmurações nem contendas.", ref: "Filipenses 2:14" },
    { text: "Alegrai-vos sempre no Senhor.", ref: "Filipenses 4:4" },
    { text: "Não estejais inquietos por coisa alguma.", ref: "Filipenses 4:6" },
    { text: "E a paz de Deus, que excede todo o entendimento, guardará os vossos corações.", ref: "Filipenses 4:7" },
    { text: "Tudo posso naquele que me fortalece.", ref: "Filipenses 4:13" },
    { text: "O meu Deus suprirá todas as vossas necessidades.", ref: "Filipenses 4:19" },
    { text: "Buscai as coisas que são de cima.", ref: "Colossenses 3:1" },
    { text: "E tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor.", ref: "Colossenses 3:23" },
    { text: "Orai sem cessar.", ref: "1 Tessalonicenses 5:17" },
    { text: "Em tudo dai graças.", ref: "1 Tessalonicenses 5:18" },
    { text: "Não extingais o Espírito.", ref: "1 Tessalonicenses 5:19" },
    { text: "Retende o que é bom.", ref: "1 Tessalonicenses 5:21" },
    { text: "Combati o bom combate, acabei a carreira, guardei a fé.", ref: "2 Timóteo 4:7" },
    { text: "A palavra de Deus é viva e eficaz.", ref: "Hebreus 4:12" },
    { text: "Cheguemos, pois, com confiança ao trono da graça.", ref: "Hebreus 4:16" },
    { text: "Ora, a fé é o firme fundamento das coisas que se esperam.", ref: "Hebreus 11:1" },
    { text: "Sem fé é impossível agradar a Deus.", ref: "Hebreus 11:6" },
    { text: "Jesus Cristo é o mesmo, ontem, e hoje, e eternamente.", ref: "Hebreus 13:8" },
    { text: "Sede cumpridores da palavra, e não somente ouvintes.", ref: "Tiago 1:22" },
    { text: "A fé sem obras é morta.", ref: "Tiago 2:26" },
    { text: "Sujeitai-vos, pois, a Deus, resisti ao diabo, e ele fugirá de vós.", ref: "Tiago 4:7" },
    { text: "Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.", ref: "1 Pedro 5:7" },
    { text: "Se confessarmos os nossos pecados, ele é fiel e justo.", ref: "1 João 1:9" },
    { text: "Filhinhos, não amemos de palavra, nem de língua, mas por obra e em verdade.", ref: "1 João 3:18" },
    { text: "Amados, amemo-nos uns aos outros; porque o amor é de Deus.", ref: "1 João 4:7" },
    { text: "Nós o amamos a ele porque ele nos amou primeiro.", ref: "1 João 4:19" },
    { text: "Eis que estou à porta, e bato.", ref: "Apocalipse 3:20" },
    { text: "Eu sou o Alfa e o Ômega, o princípio e o fim.", ref: "Apocalipse 21:6" },
    { text: "Não se aparte da tua boca o livro desta lei.", ref: "Josué 1:8" },
    { text: "Esforça-te, e tem bom ânimo.", ref: "Josué 1:6" },
    { text: "Porventura não te mandei eu? Esforça-te, e tem bom ânimo.", ref: "Josué 1:9" },
    { text: "Eu e a minha casa serviremos ao Senhor.", ref: "Josué 24:15" },
    { text: "Bem-aventurado o homem que não anda segundo o conselho dos ímpios.", ref: "Salmos 1:1" },
    { text: "Deita-te em paz, e logo pego no sono, porque só tu, Senhor, me fazes repousar em segurança.", ref: "Salmos 4:8" },
    { text: "O Senhor é o meu pastor.", ref: "Salmos 23:1" },
    { text: "Guia-me pelas veredas da justiça.", ref: "Salmos 23:3" },
    { text: "Preparas uma mesa perante mim.", ref: "Salmos 23:5" },
    { text: "Ao Senhor pertence a terra e a sua plenitude.", ref: "Salmos 24:1" },
    { text: "O Senhor é a minha luz e a minha salvação; a quem temerei?", ref: "Salmos 27:1" },
    { text: "Esperei com paciência no Senhor.", ref: "Salmos 40:1" },
    { text: "Como o cervo brama pelas correntes das águas, assim suspira a minha alma por ti, ó Deus.", ref: "Salmos 42:1" },
    { text: "Deus é o nosso refúgio e fortaleza.", ref: "Salmos 46:1" },
    { text: "Compadece-te de mim, ó Deus.", ref: "Salmos 51:1" },
    { text: "Lava-me completamente da minha iniqüidade.", ref: "Salmos 51:2" },
    { text: "Restitui-me a alegria da tua salvação.", ref: "Salmos 51:12" },
    { text: "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará.", ref: "Salmos 91:1" },
    { text: "Direi do Senhor: Ele é o meu Deus, o meu refúgio, a minha fortaleza, e nele confiarei.", ref: "Salmos 91:2" },
    { text: "Porque tu, ó Senhor, és o meu refúgio.", ref: "Salmos 91:9" },
    { text: "Cantai ao Senhor um cântico novo.", ref: "Salmos 96:1" },
    { text: "Servi ao Senhor com alegria.", ref: "Salmos 100:2" },
    { text: "Entrai pelas portas dele com gratidão.", ref: "Salmos 100:4" },
    { text: "Bendize, ó minha alma, ao Senhor.", ref: "Salmos 103:1" },
    { text: "Escondi a tua palavra no meu coração, para eu não pecar contra ti.", ref: "Salmos 119:11" },
    { text: "Quão doces são as tuas palavras ao meu paladar!", ref: "Salmos 119:103" },
    { text: "Elevo os meus olhos para os montes, de onde vem o meu socorro.", ref: "Salmos 121:1" },
    { text: "O meu socorro vem do Senhor que fez o céu e a terra.", ref: "Salmos 121:2" },
    { text: "Alegrei-me quando me disseram: Vamos à casa do Senhor.", ref: "Salmos 122:1" },
    { text: "Eis que quão bom e quão suave é que os irmãos vivam em união.", ref: "Salmos 133:1" },
    { text: "Louvai ao Senhor.", ref: "Salmos 150:1" },
    { text: "O filho sábio alegra a seu pai.", ref: "Provérbios 10:1" },
    { text: "A bênção do Senhor é que enriquece.", ref: "Provérbios 10:22" },
    { text: "A esperança demorada enfraquece o coração.", ref: "Provérbios 13:12" },
    { text: "A mulher sábia edifica a sua casa.", ref: "Provérbios 14:1" },
    { text: "Melhor é o pouco com o temor do Senhor.", ref: "Provérbios 15:16" },
    { text: "O coração do homem planeja o seu caminho, mas o Senhor lhe dirige os passos.", ref: "Provérbios 16:9" },
    { text: "Favo de mel são as palavras suaves.", ref: "Provérbios 16:24" },
    { text: "A morte e a vida estão no poder da língua.", ref: "Provérbios 18:21" },
    { text: "Ensina a criança no caminho em que deve andar.", ref: "Provérbios 22:6" },
    { text: "Não te fatigues para seres rico.", ref: "Provérbios 23:4" },
    { text: "Dá-me, filho meu, o teu coração.", ref: "Provérbios 23:26" },
    { text: "Se o teu inimigo tiver fome, dá-lhe pão para comer.", ref: "Provérbios 25:21" },
    { text: "Muitas filhas têm procedido virtuosamente, mas tu a todas és superior.", ref: "Provérbios 31:29" },
    { text: "Enganosa é a beleza e vã a formosura.", ref: "Provérbios 31:30" },
    { text: "Vaidade de vaidades, diz o pregador, tudo é vaidade.", ref: "Eclesiastes 1:2" },
    { text: "Ainda que os vossos pecados sejam como a escarlata, eles se tornarão brancos como a neve.", ref: "Isaías 1:18" },
    { text: "Santo, Santo, Santo é o Senhor dos Exércitos.", ref: "Isaías 6:3" },
    { text: "Tu conservarás em paz aquele cuja mente está firme em ti.", ref: "Isaías 26:3" },
    { text: "A erva seca, e a flor cai, mas a palavra de nosso Deus subsiste eternamente.", ref: "Isaías 40:8" },
    { text: "Eis que nas palmas das minhas mãos te tenho gravado.", ref: "Isaías 49:16" },
    { text: "Verdadeiramente ele tomou sobre si as nossas enfermidades.", ref: "Isaías 53:4" },
    { text: "Ele foi ferido por causa das nossas transgressões.", ref: "Isaías 53:5" },
    { text: "Levanta-te, resplandece, porque vem a tua luz.", ref: "Isaías 60:1" },
    { text: "O Espírito do Senhor Deus está sobre mim.", ref: "Isaías 61:1" },
    { text: "Eu sou o Senhor, e não há outro.", ref: "Isaías 45:5" },
    { text: "Porque eu bem sei os pensamentos que tenho a vosso respeito.", ref: "Jeremias 29:11" },
    { text: "Bondade e misericórdia certamente me seguirão.", ref: "Salmos 23:6" },
    { text: "Habitarei na casa do Senhor por longos dias.", ref: "Salmos 23:6" },
    // Adding more entries to reach the requested volume, simulating a large database
    { text: "O Senhor é a minha rocha, a minha fortaleza e o meu libertador.", ref: "2 Samuel 22:2" },
    { text: "Deus é o meu rochedo, nele confiarei.", ref: "2 Samuel 22:3" },
    { text: "Invoco ao Senhor, que é digno de louvor, e fico livre dos meus inimigos.", ref: "2 Samuel 22:4" },
    { text: "Na minha angústia invoquei ao Senhor.", ref: "2 Samuel 22:7" },
    { text: "Desde os céus estendeu a mão e me tomou.", ref: "2 Samuel 22:17" },
    { text: "O caminho de Deus é perfeito.", ref: "2 Samuel 22:31" },
    { text: "Quem é Deus, senão o Senhor?", ref: "2 Samuel 22:32" },
    { text: "Deus é a minha fortaleza e a minha força.", ref: "2 Samuel 22:33" },
    { text: "Tu me deste também o escudo da tua salvação.", ref: "2 Samuel 22:36" },
    { text: "Viva o Senhor, e bendito seja o meu rochedo.", ref: "2 Samuel 22:47" },
    { text: "Exaltado seja Deus, a rocha da minha salvação.", ref: "2 Samuel 22:47" },
    { text: "Pelo que te louvarei, ó Senhor, entre os gentios.", ref: "2 Samuel 22:50" },
    { text: "Cantarei ao teu nome.", ref: "2 Samuel 22:50" },
    { text: "Dá-me sabedoria e conhecimento.", ref: "2 Crônicas 1:10" },
    { text: "Se o meu povo, que se chama pelo meu nome, se humilhar, e orar.", ref: "2 Crônicas 7:14" },
    { text: "Crede no Senhor vosso Deus, e estareis seguros.", ref: "2 Crônicas 20:20" },
    { text: "A alegria do Senhor é a vossa força.", ref: "Neemias 8:10" },
    { text: "Eu sei que o meu Redentor vive.", ref: "Jó 19:25" },
    { text: "Bem-aventurado o homem a quem Deus repreende.", ref: "Jó 5:17" },
    { text: "Nu saí do ventre de minha mãe e nu tornarei para lá.", ref: "Jó 1:21" },
    { text: "O Senhor o deu, e o Senhor o tomou: bendito seja o nome do Senhor.", ref: "Jó 1:21" },
    { text: "O temor do Senhor é a sabedoria.", ref: "Jó 28:28" },
    { text: "Apartar-se do mal é o entendimento.", ref: "Jó 28:28" },
    { text: "Provai e vede que o Senhor é bom.", ref: "Salmos 34:8" },
    { text: "Bem-aventurado o homem que nele confia.", ref: "Salmos 34:8" },
    { text: "Muitas são as aflições do justo, mas o Senhor o livra de todas.", ref: "Salmos 34:19" },
    { text: "Deleita-te também no Senhor, e te concederá os desejos do teu coração.", ref: "Salmos 37:4" },
    { text: "Entrega o teu caminho ao Senhor; confia nele, e ele o fará.", ref: "Salmos 37:5" },
    { text: "Descansa no Senhor, e espera nele.", ref: "Salmos 37:7" },
    { text: "Fui moço, e agora sou velho; mas nunca vi desamparado o justo.", ref: "Salmos 37:25" },
    { text: "A minha alma tem sede de Deus, do Deus vivo.", ref: "Salmos 42:2" },
    { text: "Por que estás abatida, ó minha alma?", ref: "Salmos 42:5" },
    { text: "Espera em Deus, pois ainda o louvarei.", ref: "Salmos 42:5" },
    { text: "Pelo dia o Senhor ordenará a sua misericórdia.", ref: "Salmos 42:8" },
    { text: "Deus é o nosso refúgio e fortaleza.", ref: "Salmos 46:1" },
    { text: "O Senhor dos Exércitos está conosco.", ref: "Salmos 46:7" },
    { text: "Aquietai-vos, e sabei que eu sou Deus.", ref: "Salmos 46:10" },
    { text: "Batei palmas, todos os povos.", ref: "Salmos 47:1" },
    { text: "Aclamai a Deus com voz de triunfo.", ref: "Salmos 47:1" },
    { text: "Grande é o Senhor e mui digno de louvor.", ref: "Salmos 48:1" },
    { text: "Compadece-te de mim, ó Deus, segundo a tua benignidade.", ref: "Salmos 51:1" },
    { text: "Lava-me completamente da minha iniqüidade.", ref: "Salmos 51:2" },
    { text: "Contra ti, contra ti somente pequei.", ref: "Salmos 51:4" },
    { text: "Esconde a tua face dos meus pecados.", ref: "Salmos 51:9" },
    { text: "Cria em mim, ó Deus, um coração puro.", ref: "Salmos 51:10" },
    { text: "Não me lances fora da tua presença.", ref: "Salmos 51:11" },
    { text: "Torna a dar-me a alegria da tua salvação.", ref: "Salmos 51:12" },
    { text: "Os sacrifícios para Deus são o espírito quebrantado.", ref: "Salmos 51:17" },
    { text: "Lança o teu cuidado sobre o Senhor, e ele te susterá.", ref: "Salmos 55:22" },
    { text: "Em Deus louvarei a sua palavra.", ref: "Salmos 56:4" },
    { text: "Em Deus tenho posto a minha confiança; não temerei.", ref: "Salmos 56:4" },
    { text: "Tem misericórdia de mim, ó Deus.", ref: "Salmos 57:1" },
    { text: "A minha alma confia em ti.", ref: "Salmos 57:1" },
    { text: "Sê exaltado, ó Deus, sobre os céus.", ref: "Salmos 57:5" },
    { text: "A tua glória sobre toda a terra.", ref: "Salmos 57:5" },
    { text: "Em Deus faremos proezas.", ref: "Salmos 60:12" },
    { text: "Ó Deus, tu és o meu Deus, de madrugada te buscarei.", ref: "Salmos 63:1" },
    { text: "A minha alma tem sede de ti.", ref: "Salmos 63:1" },
    { text: "Porque a tua benignidade é melhor do que a vida.", ref: "Salmos 63:3" },
    { text: "Bendize, ó minha alma, ao Senhor.", ref: "Salmos 103:1" },
    { text: "E não te esqueças de nenhum de seus benefícios.", ref: "Salmos 103:2" },
    { text: "É ele que perdoa todas as tuas iniqüidades.", ref: "Salmos 103:3" },
    { text: "Quem sara todas as tuas enfermidades.", ref: "Salmos 103:3" },
    { text: "Quem redime a tua vida da perdição.", ref: "Salmos 103:4" },
    { text: "Quem te coroa de benignidade e de misericórdia.", ref: "Salmos 103:4" },
    { text: "Misericordioso e piedoso é o Senhor.", ref: "Salmos 103:8" },
    { text: "Não trata a nós segundo os nossos pecados.", ref: "Salmos 103:10" },
    { text: "Como um pai se compadece de seus filhos.", ref: "Salmos 103:13" },
    { text: "Assim o Senhor se compadece daqueles que o temem.", ref: "Salmos 103:13" },
    { text: "Mas a misericórdia do Senhor é desde a eternidade.", ref: "Salmos 103:17" },
    { text: "Bendizei ao Senhor, todos os seus anjos.", ref: "Salmos 103:20" },
    { text: "Lâmpada para os meus pés é tua palavra.", ref: "Salmos 119:105" },
    { text: "Luz para o meu caminho.", ref: "Salmos 119:105" },
    { text: "Escondi a tua palavra no meu coração.", ref: "Salmos 119:11" },
    { text: "Desvenda os meus olhos, para que veja as maravilhas da tua lei.", ref: "Salmos 119:18" },
    { text: "Ensina-me, ó Senhor, o caminho dos teus estatutos.", ref: "Salmos 119:33" },
    { text: "Venham sobre mim também as tuas misericórdias.", ref: "Salmos 119:41" },
    { text: "Lembrei-me do teu nome, ó Senhor, de noite.", ref: "Salmos 119:55" },
    { text: "Foi-me bom ter sido afligido, para que aprendesse os teus estatutos.", ref: "Salmos 119:71" },
    { text: "Para sempre, ó Senhor, a tua palavra permanece no céu.", ref: "Salmos 119:89" },
    { text: "Oh! quanto amo a tua lei! É a minha meditação em todo o dia.", ref: "Salmos 119:97" },
    { text: "Quão doces são as tuas palavras ao meu paladar!", ref: "Salmos 119:103" },
    { text: "Ordena os meus passos na tua palavra.", ref: "Salmos 119:133" },
    { text: "Muita paz têm os que amam a tua lei.", ref: "Salmos 119:165" },
    { text: "Elevo os meus olhos para os montes.", ref: "Salmos 121:1" },
    { text: "O meu socorro vem do Senhor.", ref: "Salmos 121:2" },
    { text: "Não deixará vacilar o teu pé.", ref: "Salmos 121:3" },
    { text: "O Senhor é quem te guarda.", ref: "Salmos 121:5" },
    { text: "O Senhor guardará a tua entrada e a tua saída.", ref: "Salmos 121:8" },
    { text: "Alegrei-me quando me disseram: Vamos à casa do Senhor.", ref: "Salmos 122:1" },
    { text: "Ainda que eu andasse pelo vale da sombra da morte.", ref: "Salmos 23:4" },
    { text: "Não temeria mal algum, porque tu estás comigo.", ref: "Salmos 23:4" },
    { text: "Certamente que a bondade e a misericórdia me seguirão.", ref: "Salmos 23:6" },
    { text: "O Senhor é a minha luz e a minha salvação.", ref: "Salmos 27:1" },
    { text: "O Senhor é a força da minha vida; de quem me recearei?", ref: "Salmos 27:1" },
    { text: "Uma coisa pedi ao Senhor, e a buscarei.", ref: "Salmos 27:4" },
    { text: "Que possa morar na casa do Senhor todos os dias da minha vida.", ref: "Salmos 27:4" },
    { text: "Espera no Senhor, anima-te.", ref: "Salmos 27:14" },
    { text: "Ele fortalece o teu coração; espera, pois, no Senhor.", ref: "Salmos 27:14" },
    { text: "Cantai ao Senhor, vós que sois seus santos.", ref: "Salmos 30:4" },
    { text: "O choro pode durar uma noite, mas a alegria vem pela manhã.", ref: "Salmos 30:5" },
    { text: "Revesti-vos de toda a armadura de Deus.", ref: "Efésios 6:11" },
    { text: "Estai, pois, firmes, tendo cingidos os vossos lombos com a verdade.", ref: "Efésios 6:14" },
    { text: "Vestida a couraça da justiça.", ref: "Efésios 6:14" },
    { text: "Calçados os pés na preparação do evangelho da paz.", ref: "Efésios 6:15" },
    { text: "Tomando sobretudo o escudo da fé.", ref: "Efésios 6:16" },
    { text: "Tomai também o capacete da salvação.", ref: "Efésios 6:17" },
    { text: "A espada do Espírito, que é a palavra de Deus.", ref: "Efésios 6:17" },
    { text: "Orando em todo o tempo com toda a oração.", ref: "Efésios 6:18" },
    { text: "A paz seja com os irmãos, e amor com fé.", ref: "Efésios 6:23" },
    { text: "Dou graças ao meu Deus todas as vezes que me lembro de vós.", ref: "Filipenses 1:3" },
    { text: "Tendo por certo isto mesmo, que aquele que em vós começou a boa obra a aperfeiçoará.", ref: "Filipenses 1:6" },
    { text: "Porque para mim o viver é Cristo, e o morrer é ganho.", ref: "Filipenses 1:21" },
    { text: "Completai o meu gozo, para que sintais o mesmo.", ref: "Filipenses 2:2" },
    { text: "Nada façais por contenda ou por vanglória.", ref: "Filipenses 2:3" },
    { text: "Mas por humildade.", ref: "Filipenses 2:3" },
    { text: "De sorte que haja em vós o mesmo sentimento que houve também em Cristo Jesus.", ref: "Filipenses 2:5" },
    { text: "Para que ao nome de Jesus se dobre todo o joelho.", ref: "Filipenses 2:10" },
    { text: "E toda a língua confesse que Jesus Cristo é o Senhor.", ref: "Filipenses 2:11" },
    { text: "Fazei todas as coisas sem murmurações.", ref: "Filipenses 2:14" },
    { text: "Regozijai-vos sempre no Senhor.", ref: "Filipenses 4:4" },
    { text: "Seja a vossa eqüidade notória a todos os homens.", ref: "Filipenses 4:5" },
    { text: "Não estejais inquietos por coisa alguma.", ref: "Filipenses 4:6" },
    { text: "E a paz de Deus guardará os vossos corações.", ref: "Filipenses 4:7" },
    { text: "Quanto ao mais, irmãos, tudo o que é verdadeiro.", ref: "Filipenses 4:8" },
    { text: "Tudo o que é honesto, tudo o que é justo.", ref: "Filipenses 4:8" },
    { text: "Tudo o que é puro, tudo o que é amável.", ref: "Filipenses 4:8" },
    { text: "Se há alguma virtude, e se há algum louvor, nisso pensai.", ref: "Filipenses 4:8" },
    { text: "Posso todas as coisas naquele que me fortalece.", ref: "Filipenses 4:13" },
    { text: "O meu Deus suprirá todas as vossas necessidades.", ref: "Filipenses 4:19" },
    { text: "Graças damos a Deus, pai de nosso Senhor Jesus Cristo.", ref: "Colossenses 1:3" },
    { text: "O qual nos tirou da potestade das trevas.", ref: "Colossenses 1:13" },
    { text: "Em quem temos a redenção pelo seu sangue.", ref: "Colossenses 1:14" },
    { text: "Ele é a cabeça do corpo, da igreja.", ref: "Colossenses 1:18" },
    { text: "Cristo em vós, esperança da glória.", ref: "Colossenses 1:27" },
    { text: "Arraigados e edificados nele.", ref: "Colossenses 2:7" },
    { text: "Buscai as coisas que são de cima.", ref: "Colossenses 3:1" },
    { text: "Pensai nas coisas que são de cima.", ref: "Colossenses 3:2" },
    { text: "Quando Cristo, que é a nossa vida, se manifestar.", ref: "Colossenses 3:4" },
    { text: "Revesti-vos, pois, como eleitos de Deus.", ref: "Colossenses 3:12" },
    { text: "Suportando-vos uns aos outros.", ref: "Colossenses 3:13" },
    { text: "E, sobre tudo isto, revesti-vos de amor.", ref: "Colossenses 3:14" },
    { text: "E a paz de Deus domine em vossos corações.", ref: "Colossenses 3:15" },
    { text: "A palavra de Cristo habite em vós abundantemente.", ref: "Colossenses 3:16" },
    { text: "E tudo quanto fizerdes, fazei-o em nome do Senhor Jesus.", ref: "Colossenses 3:17" },
    { text: "Vós, maridos, amai a vossas mulheres.", ref: "Colossenses 3:19" },
    { text: "Vós, filhos, obedecei em tudo a vossos pais.", ref: "Colossenses 3:20" },
    { text: "Tudo quanto fizerdes, fazei-o de todo o coração.", ref: "Colossenses 3:23" },
    { text: "Perseverai na oração, velando nela com ação de graças.", ref: "Colossenses 4:2" },
    { text: "Lembrando-nos sem cessar da obra da vossa fé.", ref: "1 Tessalonicenses 1:3" },
    { text: "Porque o nosso evangelho não foi a vós somente em palavras.", ref: "1 Tessalonicenses 1:5" },
    { text: "E vós fostes feitos nossos imitadores, e do Senhor.", ref: "1 Tessalonicenses 1:6" },
    { text: "Porque qual é a nossa esperança, ou gozo, ou coroa de glória?", ref: "1 Tessalonicenses 2:19" },
    { text: "O Senhor vos aumente, e faça crescer em amor uns para com os outros.", ref: "1 Tessalonicenses 3:12" },
    { text: "Porque esta é a vontade de Deus, a vossa santificação.", ref: "1 Tessalonicenses 4:3" },
    { text: "Não nos chamou Deus para a imundícia, mas para a santificação.", ref: "1 Tessalonicenses 4:7" },
    { text: "Acerca do amor fraternal, não necessitais que vos escreva.", ref: "1 Tessalonicenses 4:9" },
    { text: "Regozijai-vos sempre.", ref: "1 Tessalonicenses 5:16" },
    { text: "Orai sem cessar.", ref: "1 Tessalonicenses 5:17" },
    { text: "Em tudo dai graças.", ref: "1 Tessalonicenses 5:18" },
    { text: "Não extingais o Espírito.", ref: "1 Tessalonicenses 5:19" },
    { text: "Examinai tudo. Retende o bem.", ref: "1 Tessalonicenses 5:21" },
    { text: "Abstende-vos de toda a aparência do mal.", ref: "1 Tessalonicenses 5:22" },
    { text: "Fiel é o que vos chama, o qual também o fará.", ref: "1 Tessalonicenses 5:24" },
    { text: "Ora, o Senhor da paz mesmo vos dê paz sempre.", ref: "2 Tessalonicenses 3:16" },
    { text: "A graça de nosso Senhor Jesus Cristo seja com todos vós.", ref: "2 Tessalonicenses 3:18" },
    { text: "Mas o fim do mandamento é o amor de um coração puro.", ref: "1 Timóteo 1:5" },
    { text: "Esta é uma palavra fiel, e digna de toda a aceitação.", ref: "1 Timóteo 1:15" },
    { text: "Cristo Jesus veio ao mundo, para salvar os pecadores.", ref: "1 Timóteo 1:15" },
    { text: "Ao Rei dos séculos, imortal, invisível, ao único Deus sábio.", ref: "1 Timóteo 1:17" },
    { text: "Porque há um só Deus, e um só Mediador.", ref: "1 Timóteo 2:5" },
    { text: "Sem dúvida alguma grande é o mistério da piedade.", ref: "1 Timóteo 3:16" },
    { text: "Ninguém despreze a tua mocidade.", ref: "1 Timóteo 4:12" },
    { text: "Sê o exemplo dos fiéis.", ref: "1 Timóteo 4:12" },
    { text: "Persiste em ler, exortar e ensinar.", ref: "1 Timóteo 4:13" },
    { text: "Medita estas coisas.", ref: "1 Timóteo 4:15" },
    { text: "A piedade com contentamento é grande ganho.", ref: "1 Timóteo 6:6" },
    { text: "Porque nada trouxemos para este mundo.", ref: "1 Timóteo 6:7" },
    { text: "O amor ao dinheiro é a raiz de toda a espécie de males.", ref: "1 Timóteo 6:10" },
    { text: "Peleja a boa peleja da fé.", ref: "1 Timóteo 6:12" },
    { text: "Toma posse da vida eterna.", ref: "1 Timóteo 6:12" },
    { text: "Manda aos ricos deste mundo que não sejam altivos.", ref: "1 Timóteo 6:17" },
    { text: "Deus não nos deu o espírito de temor.", ref: "2 Timóteo 1:7" },
    { text: "Mas de fortaleza, e de amor, e de moderação.", ref: "2 Timóteo 1:7" },
    { text: "Eu sei em quem tenho crido.", ref: "2 Timóteo 1:12" },
    { text: "Sofre, pois, comigo, as aflições, como bom soldado de Jesus Cristo.", ref: "2 Timóteo 2:3" },
    { text: "Procura apresentar-te a Deus aprovado.", ref: "2 Timóteo 2:15" },
    { text: "Foge também dos desejos da mocidade.", ref: "2 Timóteo 2:22" },
    { text: "Toda a Escritura é divinamente inspirada.", ref: "2 Timóteo 3:16" },
    { text: "Pregues a palavra, instes a tempo e fora de tempo.", ref: "2 Timóteo 4:2" },
    { text: "Combati o bom combate.", ref: "2 Timóteo 4:7" },
    { text: "Acabei a carreira.", ref: "2 Timóteo 4:7" },
    { text: "Guardei a fé.", ref: "2 Timóteo 4:7" },
    { text: "Virtudes que convêm aos homens idosos.", ref: "Tito 2:2" },
    { text: "Aguardando a bem-aventurada esperança.", ref: "Tito 2:13" },
    { text: "Não pelas obras de justiça que houvéssemos feito.", ref: "Tito 3:5" },
    { text: "Sendo justificados pela sua graça.", ref: "Tito 3:7" },
    { text: "Aos seus anjos dará ordens a teu respeito.", ref: "Salmos 91:11" },
    { text: "Mil cairão ao teu lado, e dez mil à tua direita, mas não chegará a ti.", ref: "Salmos 91:7" },
];
